export type City = {
  id: string
  name: string
  countryId: string
}

export const CITIES: City[] = [
  { id: "syd", name: "Sydney", countryId: "au" },
  { id: "mel", name: "Melbourne", countryId: "au" },
  { id: "min", name: "Minsk", countryId: "by" },
  { id: "brest", name: "Brest", countryId: "by" },
  { id: "rio", name: "Rio de Janeiro", countryId: "br" },
  { id: "sao", name: "Sao Paulo", countryId: "br" },
  { id: "tor", name: "Toronto", countryId: "ca" },
  { id: "van", name: "Vancouver", countryId: "ca" },
  { id: "mon", name: "Montreal", countryId: "ca" },
  { id: "bei", name: "Beijing", countryId: "cn" },
  { id: "sha", name: "Shanghai", countryId: "cn" },
  { id: "par", name: "Paris", countryId: "fr" },
  { id: "mar", name: "Marseille", countryId: "fr" },
  { id: "ber", name: "Berlin", countryId: "de" },
  { id: "mun", name: "Munich", countryId: "de" },
  { id: "ham", name: "Hamburg", countryId: "de" },
  { id: "mum", name: "Mumbai", countryId: "in" },
  { id: "del", name: "New Delhi", countryId: "in" },
  { id: "rom", name: "Rome", countryId: "it" },
  { id: "mil", name: "Milan", countryId: "it" },
  { id: "tok", name: "Tokyo", countryId: "jp" },
  { id: "osk", name: "Osaka", countryId: "jp" },
  { id: "ala", name: "Almaty", countryId: "kz" },
  { id: "ast", name: "Astana", countryId: "kz" },
  { id: "mex", name: "Mexico City", countryId: "mx" },
  { id: "ams", name: "Amsterdam", countryId: "nl" },
  { id: "rot", name: "Rotterdam", countryId: "nl" },
  { id: "war", name: "Warsaw", countryId: "pl" },
  { id: "kra", name: "Krakow", countryId: "pl" },
  { id: "mos", name: "Moscow", countryId: "ru" },
  { id: "spb", name: "Saint Petersburg", countryId: "ru" },
  { id: "kaz", name: "Kazan", countryId: "ru" },
  { id: "nov", name: "Novosibirsk", countryId: "ru" },
  { id: "mad", name: "Madrid", countryId: "es" },
  { id: "bar", name: "Barcelona", countryId: "es" },
  { id: "ist", name: "Istanbul", countryId: "tr" },
  { id: "ank", name: "Ankara", countryId: "tr" },
  { id: "kyiv", name: "Kyiv", countryId: "ua" },
  { id: "lvi", name: "Lviv", countryId: "ua" },
  { id: "ode", name: "Odesa", countryId: "ua" },
  { id: "lon", name: "London", countryId: "gb" },
  { id: "man", name: "Manchester", countryId: "gb" },
  { id: "edin", name: "Edinburgh", countryId: "gb" },
  { id: "nyc", name: "New York", countryId: "us" },
  { id: "la", name: "Los Angeles", countryId: "us" },
  { id: "chi", name: "Chicago", countryId: "us" },
  { id: "mia", name: "Miami", countryId: "us" },
  { id: "sf", name: "San Francisco", countryId: "us" },
]
