import type {Metadata} from "next"
import {Inter} from "next/font/google"
import "./globals.css"
import {Providers} from './providers';

const inter = Inter({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}


export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={inter.variable}>
    <body>
    <Providers>
      {children}
    </Providers>
    </body>
    </html>
  )
}
