import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Header } from "@/common/components/Header/Header"
import "./globals.css"
import { Sidebar } from "@/common/components/Sidebar/Sidebar"
import styles from "./layout.module.css"
import { ReactNode } from "react"

const inter = Inter({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  const isAuth = true
  const appShellClassName = `${styles.appShell} ${!isAuth ? styles.appShellWithoutSidebar : ""}`

  return (
    <html lang="en" className={inter.variable}>
      <body>
        <Header isAuth={isAuth} />
        <div className={appShellClassName}>
          {isAuth && <Sidebar />}
          <main className={styles.appContent}>{children}</main>
        </div>
      </body>
    </html>
  )
}
